- name: Create systemd RabbitMQ limits directory
  file: path=/etc/systemd/system/rabbitmq-server.service.d state=directory

- name: Copy RabbitMQ limits configuration
  template: src=limits.conf.j2 dest=/etc/systemd/system/rabbitmq-server.service.d/limits.conf

- name: Remove the default user
  rabbitmq_user: name=guest state=absent

- name: Create a new secure RabbitMQ user
  rabbitmq_user:
    user: "{{ rabbitmq_username }}"
    password: "{{ rabbitmq_password }}"
    tags: "{{ ','.join(rabbitmq_user_tags) }}"
    permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
          state: present

- name: Enable RabbitMQ plugins
  rabbitmq_plugin:
    names: "{{ rabbitmq_plugins }}"
    state: enabled
